/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferirRouteImport } from './routes/transferir'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as DepositoRouteImport } from './routes/deposito'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BoletoRouteImport } from './routes/boleto'
import { Route as IndexRouteImport } from './routes/index'

const TransferirRoute = TransferirRouteImport.update({
  id: '/transferir',
  path: '/transferir',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositoRoute = DepositoRouteImport.update({
  id: '/deposito',
  path: '/deposito',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletoRoute = BoletoRouteImport.update({
  id: '/boleto',
  path: '/boleto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boleto': typeof BoletoRoute
  '/dashboard': typeof DashboardRoute
  '/deposito': typeof DepositoRoute
  '/extrato': typeof ExtratoRoute
  '/transferir': typeof TransferirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boleto': typeof BoletoRoute
  '/dashboard': typeof DashboardRoute
  '/deposito': typeof DepositoRoute
  '/extrato': typeof ExtratoRoute
  '/transferir': typeof TransferirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boleto': typeof BoletoRoute
  '/dashboard': typeof DashboardRoute
  '/deposito': typeof DepositoRoute
  '/extrato': typeof ExtratoRoute
  '/transferir': typeof TransferirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boleto'
    | '/dashboard'
    | '/deposito'
    | '/extrato'
    | '/transferir'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boleto' | '/dashboard' | '/deposito' | '/extrato' | '/transferir'
  id:
    | '__root__'
    | '/'
    | '/boleto'
    | '/dashboard'
    | '/deposito'
    | '/extrato'
    | '/transferir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoletoRoute: typeof BoletoRoute
  DashboardRoute: typeof DashboardRoute
  DepositoRoute: typeof DepositoRoute
  ExtratoRoute: typeof ExtratoRoute
  TransferirRoute: typeof TransferirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transferir': {
      id: '/transferir'
      path: '/transferir'
      fullPath: '/transferir'
      preLoaderRoute: typeof TransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposito': {
      id: '/deposito'
      path: '/deposito'
      fullPath: '/deposito'
      preLoaderRoute: typeof DepositoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boleto': {
      id: '/boleto'
      path: '/boleto'
      fullPath: '/boleto'
      preLoaderRoute: typeof BoletoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoletoRoute: BoletoRoute,
  DashboardRoute: DashboardRoute,
  DepositoRoute: DepositoRoute,
  ExtratoRoute: ExtratoRoute,
  TransferirRoute: TransferirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
