import { VercelRequest, VercelResponse } from "@vercel/node"

// Copie e cole os dados do seu db.json aqui:
const extrato = [
  {
    id: "1a2b",
    tipo: "Pagamento",
    descricao: "Cartão de Crédito",
    horario: "08:12",
    valor: -2002,
    icone: "CreditCardIcon",
    data: "2025-07-30",
    conta: "cartao-credito",
  },
  {
    id: "2b3c",
    tipo: "Depósito",
    descricao: "Pix recebido",
    horario: "11:45",
    valor: 350,
    icone: "AttachMoneyIcon",
    data: "2025-07-29",
    conta: "conta-corrente",
  },
  {
    id: "3c4d",
    tipo: "Transferência",
    descricao: "Envio para João",
    horario: "14:30",
    valor: -90,
    icone: "CompareArrowsIcon",
    data: "2025-07-29",
    conta: "conta-corrente",
  },
  {
    id: "4d5e",
    tipo: "Pagamento",
    descricao: "Luz",
    horario: "17:15",
    valor: -130,
    icone: "ReceiptIcon",
    data: "2025-07-28",
    conta: "conta-corrente",
  },
  {
    id: "5e6f",
    tipo: "Depósito",
    descricao: "Salário",
    horario: "09:00",
    valor: 3000,
    icone: "AttachMoneyIcon",
    data: "2025-07-28",
    conta: "conta-corrente",
  },
  {
    id: "6f7g",
    tipo: "Transferência",
    descricao: "Para Poupança",
    horario: "13:20",
    valor: -500,
    icone: "CompareArrowsIcon",
    data: "2025-07-28",
    conta: "conta-corrente",
  },
  {
    id: "7g8h",
    tipo: "Pagamento",
    descricao: "Netflix",
    horario: "22:05",
    valor: -39.9,
    icone: "ReceiptIcon",
    data: "2025-07-27",
    conta: "cartao-credito",
  },
  {
    id: "8h9i",
    tipo: "Depósito",
    descricao: "Transferência recebida",
    horario: "18:10",
    valor: 150,
    icone: "AttachMoneyIcon",
    data: "2025-07-27",
    conta: "conta-corrente",
  },
  {
    id: "9i0j",
    tipo: "Transferência",
    descricao: "Pix para Maria",
    horario: "10:42",
    valor: -75.5,
    icone: "CompareArrowsIcon",
    data: "2025-07-27",
    conta: "conta-corrente",
  },
  {
    id: "0j1k",
    tipo: "Pagamento",
    descricao: "Telefone",
    horario: "12:00",
    valor: -89.9,
    icone: "ReceiptIcon",
    data: "2025-07-26",
    conta: "cartao-credito",
  },
  {
    id: "a1b2",
    tipo: "Depósito",
    descricao: "Pix recebido",
    horario: "15:23",
    valor: 220,
    icone: "AttachMoneyIcon",
    data: "2025-07-26",
    conta: "conta-corrente",
  },
  {
    id: "b2c3",
    tipo: "Transferência",
    descricao: "Para investimento",
    horario: "08:45",
    valor: -1000,
    icone: "CompareArrowsIcon",
    data: "2025-07-26",
    conta: "conta-corrente",
  },
  {
    id: "c3d4",
    tipo: "Pagamento",
    descricao: "Spotify",
    horario: "07:30",
    valor: -19.9,
    icone: "ReceiptIcon",
    data: "2025-07-25",
    conta: "cartao-credito",
  },
  {
    id: "d4e5",
    tipo: "Depósito",
    descricao: "Reembolso",
    horario: "13:00",
    valor: 180,
    icone: "AttachMoneyIcon",
    data: "2025-07-25",
    conta: "conta-corrente",
  },
  {
    id: "e5f6",
    tipo: "Transferência",
    descricao: "Pix para Ana",
    horario: "16:20",
    valor: -40,
    icone: "CompareArrowsIcon",
    data: "2025-07-25",
    conta: "conta-corrente",
  },
  {
    id: "f6g7",
    tipo: "Pagamento",
    descricao: "Uber",
    horario: "19:05",
    valor: -22.5,
    icone: "ReceiptIcon",
    data: "2025-07-24",
    conta: "cartao-credito",
  },
  {
    id: "g7h8",
    tipo: "Depósito",
    descricao: "Devolução Loja",
    horario: "11:15",
    valor: 95,
    icone: "AttachMoneyIcon",
    data: "2025-07-24",
    conta: "conta-corrente",
  },
  {
    id: "h8i9",
    tipo: "Transferência",
    descricao: "Envio para Pedro",
    horario: "09:50",
    valor: -150,
    icone: "CompareArrowsIcon",
    data: "2025-07-24",
    conta: "conta-corrente",
  },
  {
    id: "i9j0",
    tipo: "Pagamento",
    descricao: "Amazon",
    horario: "14:35",
    valor: -280,
    icone: "ReceiptIcon",
    data: "2025-07-23",
    conta: "cartao-credito",
  },
  {
    id: "j0k1",
    tipo: "Depósito",
    descricao: "Pix recebido",
    horario: "17:25",
    valor: 410,
    icone: "AttachMoneyIcon",
    data: "2025-07-23",
    conta: "conta-corrente",
  },
  {
    id: "e3f6",
    tipo: "Depósito",
    descricao: "Conta Poupança",
    horario: "10:28",
    valor: 5044,
    icone: "AttachMoneyIcon",
    data: "2025-07-30",
    conta: "conta-poupança",
  },
  {
    id: "001",
    tipo: "Depósito",
    descricao: "Pix recebido de Ana",
    horario: "10:15",
    valor: 250.5,
    icone: "AttachMoneyIcon",
    data: "2025-07-29",
    conta: "conta-corrente",
  },
  {
    id: "002",
    tipo: "Pagamento",
    descricao: "Cartão de Crédito - Supermercado",
    horario: "15:42",
    valor: -189.9,
    icone: "CreditCardIcon",
    data: "2025-07-28",
    conta: "cartao-credito",
  },
  {
    id: "003",
    tipo: "Transferência",
    descricao: "Pix para Lucas",
    horario: "12:30",
    valor: -75,
    icone: "CompareArrowsIcon",
    data: "2025-07-28",
    conta: "conta-corrente",
  },
  {
    id: "004",
    tipo: "Depósito",
    descricao: "Reembolso plano saúde",
    horario: "11:00",
    valor: 180,
    icone: "AttachMoneyIcon",
    data: "2025-07-27",
    conta: "conta-corrente",
  },
  {
    id: "005",
    tipo: "Pagamento",
    descricao: "Conta de água",
    horario: "17:45",
    valor: -70.8,
    icone: "ReceiptIcon",
    data: "2025-07-27",
    conta: "conta-corrente",
  },
  {
    id: "006",
    tipo: "Transferência",
    descricao: "Envio para poupança",
    horario: "13:20",
    valor: -500,
    icone: "CompareArrowsIcon",
    data: "2025-07-27",
    conta: "conta-corrente",
  },
  {
    id: "007",
    tipo: "Depósito",
    descricao: "Freelance Projeto X",
    horario: "09:50",
    valor: 800,
    icone: "AttachMoneyIcon",
    data: "2025-07-26",
    conta: "conta-corrente",
  },
  {
    id: "008",
    tipo: "Pagamento",
    descricao: "Assinatura HBO Max",
    horario: "19:00",
    valor: -34.9,
    icone: "ReceiptIcon",
    data: "2025-07-26",
    conta: "cartao-credito",
  },
  {
    id: "009",
    tipo: "Transferência",
    descricao: "Pix para Clara",
    horario: "20:10",
    valor: -92,
    icone: "CompareArrowsIcon",
    data: "2025-07-26",
    conta: "conta-corrente",
  },
  {
    id: "010",
    tipo: "Pagamento",
    descricao: "Gasolina",
    horario: "14:15",
    valor: -240,
    icone: "ReceiptIcon",
    data: "2025-07-25",
    conta: "conta-corrente",
  },
  {
    id: "011",
    tipo: "Depósito",
    descricao: "Pix recebido",
    horario: "16:30",
    valor: 300,
    icone: "AttachMoneyIcon",
    data: "2025-07-25",
    conta: "conta-corrente",
  },
  {
    id: "012",
    tipo: "Pagamento",
    descricao: "Internet",
    horario: "08:40",
    valor: -120,
    icone: "ReceiptIcon",
    data: "2025-07-24",
    conta: "conta-corrente",
  },
  {
    id: "013",
    tipo: "Transferência",
    descricao: "Envio para Marcos",
    horario: "10:10",
    valor: -150,
    icone: "CompareArrowsIcon",
    data: "2025-07-24",
    conta: "conta-corrente",
  },
  {
    id: "014",
    tipo: "Depósito",
    descricao: "Venda notebook",
    horario: "11:50",
    valor: 2500,
    icone: "AttachMoneyIcon",
    data: "2025-07-24",
    conta: "conta-corrente",
  },
  {
    id: "015",
    tipo: "Pagamento",
    descricao: "Spotify",
    horario: "09:30",
    valor: -19.9,
    icone: "ReceiptIcon",
    data: "2025-07-23",
    conta: "cartao-credito",
  },
  {
    id: "016",
    tipo: "Depósito",
    descricao: "Pagamento aula extra",
    horario: "14:00",
    valor: 400,
    icone: "AttachMoneyIcon",
    data: "2025-07-23",
    conta: "conta-corrente",
  },
  {
    id: "017",
    tipo: "Pagamento",
    descricao: "Farmácia",
    horario: "13:15",
    valor: -58.7,
    icone: "ReceiptIcon",
    data: "2025-07-22",
    conta: "cartao-credito",
  },
  {
    id: "018",
    tipo: "Transferência",
    descricao: "Pix para Guilherme",
    horario: "18:05",
    valor: -110,
    icone: "CompareArrowsIcon",
    data: "2025-07-22",
    conta: "conta-corrente",
  },
  {
    id: "019",
    tipo: "Depósito",
    descricao: "Pix recebido",
    horario: "21:00",
    valor: 330,
    icone: "AttachMoneyIcon",
    data: "2025-07-22",
    conta: "conta-corrente",
  },
  {
    id: "020",
    tipo: "Pagamento",
    descricao: "IFood",
    horario: "12:00",
    valor: -89.9,
    icone: "ReceiptIcon",
    data: "2025-07-21",
    conta: "cartao-credito",
  },
]

export default function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method === "GET") {
    res.status(200).json(extrato)
  } else {
    res.status(405).json({ message: "Método não permitido" })
  }
}
